name: CI Pipeline - Build and Push Docker Images

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    REGISTRY: ghcr.io

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            # 1. preuzimanje koda iz repozitorijuma
            - name: Checkout repository
              uses: actions/checkout@v4

            # 2. Pretvaranje imena repoyitorija u mala slova lowercase
            - name: Lowercase repository name
              run: |
               echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

            # 3. Login na Github container registry GHCR
            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            # 4. Postavljanje Docker Buildx-a za napredno keshiranje
            - name: Seut up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # 5. Build and push za Backend
            - name: Build and Push Backend Image
              uses: docker/build-push-action@v5
              with:
                context: ./backend
                push: ${{ github.ref == 'refs/heads/main' }}
                tags: |
                  ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/backend:latest
                  ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/backend:${{ github.sha }}

            # 6. Build and Push za Frontend
            - name: Build and Push Frontend Image
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                push: ${{ github.ref == 'refs/heads/main' }}
                tags: |
                  ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/frontend:latest
                  ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/frontend:${{ github.sha }}